DROP TABLE IF EXISTS students;
DROP TABLE IF EXISTS admins;
DROP TABLE IF EXISTS tests;
DROP TABLE IF EXISTS questions;

CREATE TABLE IF NOT EXISTS students (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT,
	roll_number TEXT UNIQUE,
	phone_number TEXT,
	password TEXT
);

CREATE TABLE IF NOT EXISTS admins (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT,
	email_id TEXT UNIQUE,
	password TEXT
);

CREATE TABLE IF NOT EXISTS tests (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	start_time DATETIME,
	duration DATETIME,
	author TEXT,
	question_count INTEGER
);

CREATE TABLE IF NOT EXISTS questions (
	id INTEGER,
	test_id	TEXT,
	solution TEXT,
	FOREIGN KEY (test_id) REFERENCES "tests"(id)
);
